import type { Metadata } from "next";
import "./globals.scss";
import "/public/font-icon/styles.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { CompAccessProvider } from "@/utils/compAccessUtils";
import CrispChat from "@/components/CrispChat";
import 'antd/dist/reset.css';

export const metadata: Metadata = {
  title: "Verified Athletics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <CompAccessProvider>
            {children}
            <CrispChat />
          </CompAccessProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
