export interface DataType {
  key: string;
  id: string;
  fname: string;
  lname: string;
  image: string;
  imageLarge: string;
  unread: number;
  rating: number;
  avg: number;
  school: string;
  schoolIcon: string;
  academy: string;
  academyIcon: string;
  date: string;
  evaluation: string;
  div: string;
  yr: string;
  $: string;
  ht: string;
  high_school: string;
  st: string;
  wt: string;
  s: string;
  h: string;
  direction: string;
  position: string;
  tier: number;
  tierColor: string;
}

// Re-export the RecruitingBoardData type for backward compatibility
export type { RecruitingBoardData } from '../types/database';

export const columns = [
  'evaluation',
    'div',
    'yr',
    '$',
    'wt',
    'ht',
    'high_school',
    'st',
    'snaps',
    's',
    'h',
    'direction',
];

export const data: DataType[] = [
  {
    key: "1",
    id: "AX30901",
    fname: "Ralph",
    lname: "Edwards",
    image: "/pl1.png",
    imageLarge: "/plyer-b.png",
    rating: 2.4,
    unread: 2,
    avg: 99.3,
    school: "Kansas City School",
    schoolIcon: "/b.svg",
    academy: "Senior Team Manager",
    academyIcon: "/b.svg",
    date: "07/05/2016",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "WR",
    tier: 2,
tierColor: "#36C5F0"
  },
  {
    key: "2",
    id: "AX30902",
    fname: "Abigail",
    lname: "Wright",
    image: "/pl2.png",
    imageLarge: "/plyer-b.png",
    rating: 1.5,
    unread: 0,
    avg: 46.9,
    school: "Stanford University",
    schoolIcon: "/b.svg",
    academy: "Senior Team Manager",
    academyIcon: "/kg.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "WR",
    tier: 3,
tierColor: "#FF24BA"
  },
  {
    key: "3",
    id: "AX30903",
    fname: "Darlene",
    lname: "Robertson",
    image: "/pl3.png",
    imageLarge: "/plyer-b.png",
    rating: 4.2,
    unread: 0,
    avg: 25.9,
    school: "University of Melbourne",
    schoolIcon: "/cap.svg",
    academy: "Senior Team Manager",
    academyIcon: "/kg.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "WR",
    tier: 1,
tierColor: "#7363BC"
  },
  {
    key: "4",
    id: "AX30904",
    fname: "Christian",
    lname: "George",
    image: "/pl4.png",
    imageLarge: "/plyer-b.png",
    rating: 3,
    unread: 0,
    avg: 99.3,
    school: "University of Melbourne",
    schoolIcon: "/eg.svg",
    academy: "Senior Team Manager",
    academyIcon: "/a.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "WR",
    tier: 1,
tierColor: "#7363BC"
  },
  {
    key: "5",
    id: "AX30905",
    fname: "Christian",
    lname: "George",
    image: "/pl5.png",
    imageLarge: "/plyer-b.png",
    rating: 3.0,
    unread: 2,
    avg: 58.9,
    school: "Kansas City School",
    schoolIcon: "/b.svg",
    academy: "Senior Team Manager",
    academyIcon: "/a.svg",
    date: "07/05/2016",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "QB",
    tier: 2,
tierColor: "#36C5F0"
  },
  {
    key: "6",
    id: "AX30906",
    fname: "Darlene",
    lname: "Robertson",
    image: "/pl6.png",
    imageLarge: "/plyer-b.png",
    rating: 4.5,
    unread: 0,
    avg: 99.9,
    school: "Stanford University",
    schoolIcon: "/b.svg",
    academy: "Senior Team Manager",
    academyIcon: "/kg.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "QB",
    tier: 2,
tierColor: "#36C5F0"
  },
  {
    key: "7",
    id: "AX30907",
    fname: "Floyd",
    lname: "Miles",
    image: "/pl3.png",
    imageLarge: "/plyer-b.png",
    rating: 3.5,
    unread: 0,
    avg: 21.5,
    school: "University of Melbourne",
    schoolIcon: "/cap.svg",
    academy: "Senior Team Manager",
    academyIcon: "/kg.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "QB",
    tier: 2,
tierColor: "#36C5F0"
  },
  {
    key: "8",
    id: "AX30908",
    fname: "Floyd",
    lname: "Miles",
    image: "/pl2.png",
    imageLarge: "/plyer-b.png",
    rating: 4.5,
    unread: 0,
    avg: 32.3,
    school: "University of Melbourne",
    schoolIcon: "/eg.svg",
    academy: "Senior Team Manager",
    academyIcon: "/a.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "RB",
    tier: 2,
tierColor: "#36C5F0"
  },
  {
    key: "9",
    id: "AX30909",
    fname: "Floyd",
    lname: "Miles",
    image: "/pl6.png",
    imageLarge: "/plyer-b.png",
    rating: 5.0,
    unread: 2,
    avg: 43.9,
    school: "Kansas City School",
    schoolIcon: "/b.svg",
    academy: "Senior Team Manager",
    academyIcon: "/a.svg",
    date: "07/05/2016",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "RB",
    tier: 3,
tierColor: "#FF24BA"
  },
  {
    key: "10",
    id: "AX30910",
    fname: "Ralph",
    lname: "Edwards",
    image: "/pl5.png",
    imageLarge: "/plyer-b.png",
    rating: 1.5,
    unread: 0,
    avg: 67.9,
    school: "Stanford University",
    schoolIcon: "/b.svg",
    academy: "Senior Team Manager",
    academyIcon: "/kg.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "RB",
    tier: 3,
tierColor: "#FF24BA"
  },
  {
    key: "11",
    id: "AX30911",
    fname: "Floyd",
    lname: "Miles",
    image: "/pl4.png",
    imageLarge: "/plyer-b.png",
    rating: 3.2,
    unread: 0,
    avg: 31.7,
    school: "University of Melbourne",
    schoolIcon: "/cap.svg",
    academy: "Senior Team Manager",
    academyIcon: "/kg.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "TE",
    tier: 2,
tierColor: "#36C5F0"
  },
  {
    key: "12",
    id: "AX30912",
    fname: "Darlene",
    lname: "Robertson",
    image: "/pl6.png",
    imageLarge: "/plyer-b.png",
    rating: 2.4,
    unread: 0,
    avg: 99.9,
    school: "University of Melbourne",
    schoolIcon: "/eg.svg",
    academy: "Senior Team Manager",
    academyIcon: "/a.svg",
    date: "12/06/2020",
    evaluation: "Some Info",
    div: "D2",
    yr: "Jr",
    $: "Yes",
    wt: "215",
    ht: "1374",
    high_school: "Sidwell Friends School",
    st: "NV",
    s: "540",
    h: "Y",
    direction: "Flat",
    position: "OGC",
    tier: 1,
tierColor: "#7363BC"
  },
];


export const dataMap = data.reduce((map, item) => {
  map[item.id] = item;
  return map;
}, {} as Record<string, typeof data[0]>);